### ISSUE TITLE
Program of Quick Sort Method

### ISSUE THREAD

**Issue by atingarg1406** [atingarg1406/Data-Structure-and-Algorithms#1]
A program of Quick Sort is required in any language.

**Comment by jessicasalbert** [comment]
I can work on this if you don't mine assigning it to me :) Thanks!

**Comment by gaurangisinha** [comment]
Hello, @atingarg1406 I am very keen on contributing to this issue in C++ or C, could you please assign it to me?

**Comment by atingarg1406** [comment]
> I can work on this if you don't mine assigning it to me :) Thanks!

You can proceed @jessicasalbert

**Comment by jatinagg2** [comment]
I would like to do this task. I will implement this program in C++. Do assign me for that @atingarg1406

**Comment by atingarg1406** [comment]
> I would like to do this task. I will implement this program in C++. Do assign me for that @atingarg1406

You can proceed @jatinagg2

**Comment by jainsarthak216** [comment]
I would like to do this task in C.
