### ISSUE TITLE
Program of Insertion Sort, Selection Sort and Bubble Sort

### ISSUE THREAD

**Issue by atingarg1406** [atingarg1406/Data-Structure-and-Algorithms#4]
A program of Insertion Sort, Selection Sort and Bubble Sort is required in any language.
The program should be coded properly without any extra spaces in between.
The name of the program should be in CamelCase form.
It must lie in appropriate repository.

**Comment by jatinagg2** [comment]
I can do it. Assign the task @atingarg1406

**Comment by atingarg1406** [comment]
You can proceed @jatinagg2

**Comment by jainsarthak216** [comment]
Assign task to me in C language @atingarg1406 .

**Comment by Suraj1199** [comment]
@atingarg1406 the work was assigned to @jatinagg2 11 hours ago and still not completed. Can you reassign it to me . I have written these sorting algorithms many times and have a good hold of them. Also I can write the programs in  (Python, C, C++, Java) whichever you want.

**Comment by Sindhu-321** [comment]
May I get this issue assigned? Thanks
