### ISSUE TITLE
Program for Merge Sort

### ISSUE THREAD

**Issue by atingarg1406** [atingarg1406/Data-Structure-and-Algorithms#5]
A program of Merge Sort is required in any language.
The program should be coded properly without any extra spaces in between.
The name of the program should be in CamelCase form.
It must lie in appropriate repository.

**Comment by jatinagg2** [comment]
I would like to do this task. Do assign me for that @atingarg1406

**Comment by atingarg1406** [comment]
> I would like to do this task. Do assign me for that @atingarg1406

You can do @jatinagg2

**Comment by sderacy** [comment]
Hello! Can you assign me this so I can do a Merge Sort in Java?
