### ISSUE TITLE
Program to implement Circular Queue and its operation.

### ISSUE THREAD

**Issue by atingarg1406** [atingarg1406/Data-Structure-and-Algorithms#6]
A program to implement Circular Queue is required in any language.
The program should be coded properly without any extra spaces in between.
The name of the program should be in CamelCase form.
It must lie in appropriate repository.

**Comment by jatinagg2** [comment]
I would like to do this task. I will implement the program in C++. Do assign me for that @atingarg1406

**Comment by atingarg1406** [comment]
> I would like to do this task. I will implement the program in C++. Do assign me for that @atingarg1406

You can do @jatinagg2

**Comment by Sindhu-321** [comment]
Can I get assigned this? I am interested in doing this task Thanks.
